# SPDX-License-Identifier: Unlicense

if (OPENSSL_ASM)
    if ( OPENSSL_TARGET_ARCH STREQUAL "x64" )
        set(LIBCRYPTO_CURRENTDIR_CFLAGS ${LIBCRYPTO_CURRENTDIR_CFLAGS} "-DSHA1_ASM" "-DSHA256_ASM" "-DSHA512_ASM" "-DKECCAK1600_ASM")
    elseif ( OPENSSL_TARGET_ARCH STREQUAL "x86" )
        set(LIBCRYPTO_CURRENTDIR_CFLAGS ${LIBCRYPTO_CURRENTDIR_CFLAGS} "-DSHA1_ASM" "-DSHA256_ASM" "-DSHA512_ASM")
    elseif ( OPENSSL_TARGET_ARCH STREQUAL "arm32" )
        set(LIBCRYPTO_CURRENTDIR_CFLAGS ${LIBCRYPTO_CURRENTDIR_CFLAGS} "-DSHA1_ASM" "-DSHA256_ASM" "-DSHA512_ASM" "-DKECCAK1600_ASM")
    elseif ( OPENSSL_TARGET_ARCH STREQUAL "arm64" )
        set(LIBCRYPTO_CURRENTDIR_CFLAGS ${LIBCRYPTO_CURRENTDIR_CFLAGS} "-DSHA1_ASM" "-DSHA256_ASM" "-DSHA512_ASM" "-DKECCAK1600_ASM")
    endif()
endif()
