# SPDX-License-Identifier: Unlicense

set(LIBCRYPTO_CURRENTDIR_SOURCES
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_object.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_bitstr.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_utctm.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_gentm.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_time.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_int.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_octet.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_print.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_type.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_set.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_dup.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_d2i_fp.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_i2d_fp.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_enum.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_utf8.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_sign.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_digest.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_verify.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_mbstr.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_strex.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_algor.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_val.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_pubkey.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_sig.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_req.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_attrib.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_bignum.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_long.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_name.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_x509.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_x509a.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_crl.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_info.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_spki.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/nsseq.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_nx509.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/d2i_pu.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/d2i_pr.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/i2d_pu.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/i2d_pr.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/t_req.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/t_x509.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/t_x509a.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/t_crl.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/t_pkey.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/t_spki.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/t_bitst.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/tasn_new.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/tasn_fre.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/tasn_enc.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/tasn_dec.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/tasn_utl.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/tasn_typ.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/tasn_prn.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/ameth_lib.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/f_int.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/f_string.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/n_pkey.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/f_enum.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_pkey.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_bool.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/x_exten.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/bio_asn1.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/bio_ndef.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/asn_mime.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/asn1_gen.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/asn1_par.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/asn1_lib.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/asn1_err.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_bytes.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/a_strnid.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/evp_asn1.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/asn_pack.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/p5_pbe.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/p5_pbev2.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/p8_pkey.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/asn_moid.c
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/asn1.h
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/asn1_mac.h
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/asn1t.h
    ${CMAKE_SOURCE_DIR}/openssl/crypto/asn1/asn1_locl.h
)
