
get_filename_component(LIBCRYPTO_CURRENTDIR ${CMAKE_CURRENT_LIST_FILE} NAME_WE)

set(ENGINE_${LIBCRYPTO_CURRENTDIR}_SOURCES
    ${CMAKE_SOURCE_DIR}/openssl/engines/e_cswift.c
    ${CMAKE_SOURCE_DIR}/openssl/engines/e_cswift_err.h
)

set(ENGINE_SOURCES ${ENGINE_SOURCES} ${ENGINE_${LIBCRYPTO_CURRENTDIR}_SOURCES})
unset(LIBCRYPTO_CURRENTDIR)
