name: CMake

on: [push]

env:
  FS_OPENSSL_VERSION_STR: "1.0.2u"

jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ver: "20.04"
            codename: "focal"
          - ver: "22.04"
            codename: "jammy"
        asm: [ "YES", "NO" ]
        zlib: [ "YES", "NO" ]
    continue-on-error: true
    runs-on: ubuntu-${{ matrix.runner.ver }}
    name: "build-ubuntu-${{ matrix.runner.ver }} (ASM: ${{ matrix.asm }}, Zlib: ${{ matrix.zlib }})"
    env:
      FS_OPENSSL_PACKAGE_STR: openssl${{ env.FS_OPENSSL_VERSION_STR }}-Ubuntu${{ matrix.runner.ver }}-x86_64-ASM${{ matrix.asm }}-Zlib${{ matrix.zlib }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          path: openssl-externalCMake
      - name: add CMake repository and needed softwares
        run: |
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ ${{ matrix.runner.codename }} main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
          sudo apt-get update
          sudo apt-get install cmake ninja-build perl build-essential zlib1g-dev
      - name: run CMake + Ninja
        run: |
          mkdir -p "build"
          cd "build"
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/${{ env.FS_OPENSSL_PACKAGE_STR }}" -DOPENSSL_ASM=${{ matrix.asm }} -DOPENSSL_ZLIB=${{ matrix.zlib }} "${{ github.workspace }}/openssl-externalCMake"
          ninja
          cmake --install . --strip
      - name: run test
        run: |
          cd "build"
          ninja check
      - name: package
        run: |
          tar -cJf "${{ env.FS_OPENSSL_PACKAGE_STR }}.tar.xz" "${{ env.FS_OPENSSL_PACKAGE_STR }}"
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.FS_OPENSSL_PACKAGE_STR }}
          path: ${{ env.FS_OPENSSL_PACKAGE_STR }}.tar.xz

  build-macOS:
    strategy:
      fail-fast: false
      matrix:
        runner: [ "11", "12" ]
        asm: [ "YES", "NO" ]
        zlib: [ "YES", "NO" ]
    continue-on-error: true
    runs-on: macos-${{ matrix.runner }}
    name: "build-macOS${{ matrix.runner }} (ASM: ${{ matrix.asm }}, Zlib: ${{ matrix.zlib }})"
    env:
      FS_OPENSSL_PACKAGE_STR: openssl${{ env.FS_OPENSSL_VERSION_STR }}-macOS${{ matrix.runner.ver }}-x86_64-ASM${{ matrix.asm }}-Zlib${{ matrix.zlib }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          path: openssl-externalCMake
      - name: install cmake and ninja
        run: |
          brew update
          brew install cmake ninja
      - name: run CMake + Ninja
        run: |
          mkdir -p "build"
          cd "build"
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/${{ env.FS_OPENSSL_PACKAGE_STR }}" -DOPENSSL_ASM=${{ matrix.asm }} -DOPENSSL_ZLIB=${{ matrix.zlib }} "${{ github.workspace }}/openssl-externalCMake"
          ninja
          cmake --install . --strip
      - name: run test
        run: |
          cd "build"
          ninja check
      - name: package
        run: |
          tar -cJf "${{ env.FS_OPENSSL_PACKAGE_STR }}.tar.xz" "${{ env.FS_OPENSSL_PACKAGE_STR }}"
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.FS_OPENSSL_PACKAGE_STR }}
          path: ${{ env.FS_OPENSSL_PACKAGE_STR }}.tar.xz

  build-MinGW:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - version: "11.2.0"
            bit: "64"
            arch: "x86_64"
            url: "https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev4/x86_64-11.2.0-release-posix-seh-rt_v9-rev4.7z"
          - version: "11.2.0"
            bit: "32"
            arch: "i686"
            url: "https://github.com/cristianadam/mingw-builds/releases/download/v11.2.0-rev4/i686-11.2.0-release-posix-dwarf-rt_v9-rev4.7z"
          - version: "12.1.0"
            bit: "64"
            arch: "x86_64"
            url: "https://github.com/cristianadam/mingw-builds/releases/download/v12.1.0-rev0/x86_64-12.1.0-release-posix-seh-rt_v10-rev0.7z"
        asm: [ "YES", "NO" ]
    continue-on-error: true
    runs-on: windows-latest
    name: "build-MinGW-GCC${{ matrix.toolchain.version }}-${{ matrix.toolchain.bit }}bit (ASM: ${{ matrix.asm }})"
    env:
      FS_OPENSSL_PACKAGE_STR: openssl${{ env.FS_OPENSSL_VERSION_STR }}-MinGWGCC${{ matrix.toolchain.version }}-${{ matrix.toolchain.arch }}-ASM${{ matrix.asm }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          path: openssl-externalCMake
      - name: add CMake repository and needed softwares
        run: |
          choco install cmake
          choco install ninja
      - name: install MinGW toolchain
        run: |
          New-Item -Path "." -Name "mingw" -ItemType "directory";
          (New-Object System.Net.WebClient).DownloadFile("${{ matrix.toolchain.url }}","mingw/mingw.7z");
          cmd /c cd mingw "&&" 7z x mingw.7z
      - name: run CMake + Ninja
        shell: cmd
        run: |
          del /s /q C:\Strawberry\perl\bin\pkg-config.bat
          set path=${{ github.workspace }}\mingw\mingw${{ matrix.toolchain.bit }}\\bin;%path%
          mkdir -p "build"
          cd "build"
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/${{ env.FS_OPENSSL_PACKAGE_STR }}" -DOPENSSL_ASM=${{ matrix.asm }} "${{ github.workspace }}/openssl-externalCMake"
          ninja
          cmake --install . --strip
      - name: run test
        shell: cmd
        run: |
          set path=${{ github.workspace }}\mingw\mingw${{ matrix.toolchain.bit }}\\bin;%path%
          cd "build"
          ninja check
      - name: package
        run: |
          7z a "${{ env.FS_OPENSSL_PACKAGE_STR }}.7z" "${{ env.FS_OPENSSL_PACKAGE_STR }}"
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.FS_OPENSSL_PACKAGE_STR }}
          path: ${{ env.FS_OPENSSL_PACKAGE_STR }}.7z

  build-msvc:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - version: "2022"
            runson: "2022"
            call: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            bit: "64"
            arch: "x86_64"
          - version: "2019"
            runson: "2019"
            call: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
            bit: "64"
            arch: "x86_64"
          - version: "2019"
            runson: "2019"
            call: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsamd64_x86.bat
            bit: "32"
            arch: "i686"
        asm:
          - value: "NO"
            nasm: "NO"
          - value: "YES"
            nasm: "NO"
          - value: "YES"
            nasm: "YES"
    continue-on-error: true
    runs-on: windows-${{ matrix.toolchain.runson }}
    name: "build-MSVC${{ matrix.toolchain.version }}-${{ matrix.toolchain.bit }}bit (ASM: ${{ matrix.asm.value }}, NASM: ${{ matrix.asm.nasm }})"
    env:
      FS_OPENSSL_PACKAGE_STR: openssl${{ env.FS_OPENSSL_VERSION_STR }}-MSVC${{ matrix.toolchain.version }}-${{ matrix.toolchain.arch }}-ASM${{ matrix.asm.value }}-NASM${{ matrix.asm.nasm }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          path: openssl-externalCMake
      - name: add CMake repository and needed softwares
        run: |
          choco install cmake
          choco install ninja
          choco install nasm
      - name: run CMake + Ninja
        shell: cmd
        run: |
          del /s /q C:\Strawberry\perl\bin\pkg-config.bat
          call "${{ matrix.toolchain.call }}"
          mkdir -p "build"
          cd "build"
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/${{ env.FS_OPENSSL_PACKAGE_STR }}" -DOPENSSL_ASM=${{ matrix.asm.value }} -DOPENSSL_NASM=${{ matrix.asm.nasm }} "${{ github.workspace }}/openssl-externalCMake"
          ninja
          cmake --install . --strip
      - name: run test
        shell: cmd
        run: |
          call "${{ matrix.toolchain.call }}"
          cd "build"
          ninja check
      - name: package
        run: |
          7z a "${{ env.FS_OPENSSL_PACKAGE_STR }}.7z" "${{ env.FS_OPENSSL_PACKAGE_STR }}"
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.FS_OPENSSL_PACKAGE_STR }}
          path: ${{ env.FS_OPENSSL_PACKAGE_STR }}.7z
